name: UI Tests with Allure Report

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout GitHub Pages with history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Chrome and Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium chromium-driver default-jre wget unzip
          sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome
          sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome-stable
          echo "CHROME_BIN=/usr/bin/chromium" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

          wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.zip
          unzip allure-2.32.0.zip -d /opt/
          sudo ln -s /opt/allure-2.32.0/bin/allure /usr/local/bin/allure

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set report path
        id: report-path
        run: echo "path=builds/tests/$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Run tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: pytest tests/test_release_types.py -v --headless --alluredir=allure-results --capture=no || true

      - name: Generate Allure Report
        uses: andgineer/allure-report@v3.6
        id: allure-report
        if: always()
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: ${{ steps.report-path.outputs.path }}

      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: "#general"
          ALLURE_REPORT_URL: https://kino1703.github.io/Tafel_Ui/${{ steps.report-path.outputs.path }}/
        run: |
          python send_allure_to_slack.py
